### ISSUE TITLE
commented imports output

### ISSUE THREAD

**Issue by raxitsheth** [TLevesque/import-2-require#5]
Hi 

Small issues, when multiple line imports and in between some imports are commented, output either should be as it was or commented. 

e.g.
**Input**
import { request } from 'https';
// const fetch = require('node-fetch');
import { fs } from 'fs';

**output**
const request = require('https').request;
require('node-fetch'); _<-- Nice to have this commented._ Or left unprocessed
const fs = require('fs').fs;

**Comment by TLevesque** [comment]
Hi, in this case, you have to select only the line you want to convert. But if you want to add this feature pull requests are welcome.
